### ISSUE TITLE
Rotation of device while blur active freezes app

### ISSUE THREAD

**Issue by richwaters** [ML-Works/Bluuur#6]
- Run the Blurr example app
- With the blur visible, rotate the device
- The app no longer accepts user input

**Comment by k06a** [comment]
Looks like this is iOS10-related issue: http://stackoverflow.com/questions/38458170/ios-10-app-if-were-in-the-real-pre-commit-handler-we-cant-actually-add-any

But we need to solve it. Maybe tracking interface orientation and turning paused animation off and on again.

**Comment by k06a** [comment]
@richwaters fixed in 0.2.0 version! Thanks for reporting!
