### ISSUE TITLE
Declaration shows local variable warning

### ISSUE THREAD

**Issue by richwaters** [ML-Works/Bluuur#7]
When the "Hidden variables" warning is enabled in Xcode, the "Declaration shadows local variabled"  warning is generated when compiling MLWLiveBlurView.m

This has to do with the way weakSelf is assigned to self.  Using weakSelf directly solves the issue.

**Comment by k06a** [comment]
@richwaters thank you, I'll solve this issue as soon as possible! Or will be happy to merge your PR :)

**Comment by k06a** [comment]
@richwaters fixed in 0.2.0 version! Thanks for reporting!
